name: Build App for Windows

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build App for Windows
        run: npm run build:win
