name: Build App for Windows

on:
  workflow_dispatch:

jobs:
  build-window:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Build App for Windows
        run: npm run build:win

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifacts
          path: dist/
